### ISSUE TITLE
Missing History DB Initialization

### ISSUE THREAD

**Issue by RachitKeertiDas** [khainb/BoMb-OT#1]
Dear Authors,

This issue pertains to the ABC section of this repository. 
While trying to run the code to reproduce some of the results, we ran into issues with `pyabc`'s History DB needing initialization.
This needs a call to `abc.new()` which is missing in the current version. However, this call was present in the initial commit.

We believe that this by removed by mistake in the reformatting commit (08ee44ff7631d5a33027da342826dd6d78e8f626).
I'll file a PR shortly for fixing this issue, along with some other minor fixes which helped us run the code.
We thank you very much for providing this repository. 

Thanks and Regards,
Rachit.

**Comment by khainb** [comment]
Thank you very much for helping us fix the issue. I have just merged the pull request!
